# Semantic Release Configuration for Puppet Modules
#
# Copy this file to the root of your Puppet module repository as .releaserc.yml
#
# This configuration will:
# - Analyze commits based on Conventional Commits
# - Determine the next version (major.minor.patch)
# - Update metadata.json with the new version
# - Generate/update CHANGELOG.md
# - Create a Git tag
# - Create a GitHub Release with release notes
# - Commit changes back to main branch

branches:
  - main
  - master

# Plugins are executed in the order defined here
plugins:
  # 1. Analyze commits to determine release type
  - "@semantic-release/commit-analyzer"

  # 2. Generate release notes from commits
  - "@semantic-release/release-notes-generator"

  # 3. Update CHANGELOG.md with new release notes
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
      changelogTitle: "# Changelog\n\nAll notable changes to this project will be documented in this file. See [Conventional Commits](https://conventionalcommits.org) for commit guidelines."

  # 4. Update version in metadata.json
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files:
            - "metadata.json"
          from: '"version": ".*"'
          to: '"version": "${nextRelease.version}"'
          results:
            - file: "metadata.json"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true

  # 5. Commit the changes (CHANGELOG.md and metadata.json)
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
        - "metadata.json"
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  # 6. Create GitHub Release
  - "@semantic-release/github"

# Commit analyzer configuration
# Determines which commits trigger which release type
preset: "conventionalcommits"
releaseRules:
  - type: "feat"
    release: "minor"
  - type: "fix"
    release: "patch"
  - type: "perf"
    release: "patch"
  - type: "refactor"
    release: "patch"
  - type: "docs"
    release: false
  - type: "style"
    release: false
  - type: "test"
    release: false
  - type: "build"
    release: false
  - type: "ci"
    release: false
  - type: "chore"
    release: false
  - type: "revert"
    release: "patch"
  # Breaking changes (BREAKING CHANGE: in commit body or ! after type)
  - breaking: true
    release: "major"

# Changelog generation configuration
writerOpts:
  groupBy: "type"
  commitGroupsSort: "title"
  commitsSort: "header"
